package com.todo.dao;

import com.todo.dataobject.TodoUser;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface TodoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_user
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    @Delete({
        "delete from todo_user",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_user
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    @Insert({
        "insert into todo_user (id, gmt_created, ",
        "gmt_modified, pwd, ",
        "encrypt, lastpwd, ",
        "pwdlength, slat)",
        "values (#{id,jdbcType=VARCHAR}, #{gmtCreated,jdbcType=TIMESTAMP}, ",
        "#{gmtModified,jdbcType=TIMESTAMP}, #{pwd,jdbcType=VARCHAR}, ",
        "#{encrypt,jdbcType=VARCHAR}, #{lastpwd,jdbcType=VARCHAR}, ",
        "#{pwdlength,jdbcType=VARCHAR}, #{slat,jdbcType=VARCHAR})"
    })
    int insert(TodoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_user
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    @Select({
        "select",
        "id, gmt_created, gmt_modified, pwd, encrypt, lastpwd, pwdlength, slat",
        "from todo_user",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="gmt_created", property="gmtCreated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="pwd", property="pwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="encrypt", property="encrypt", jdbcType=JdbcType.VARCHAR),
        @Result(column="lastpwd", property="lastpwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="pwdlength", property="pwdlength", jdbcType=JdbcType.VARCHAR),
        @Result(column="slat", property="slat", jdbcType=JdbcType.VARCHAR)
    })
    TodoUser selectByPrimaryKey(String id);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_user
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    @Select({
        "select",
        "id, gmt_created, gmt_modified, pwd, encrypt, lastpwd, pwdlength, slat",
        "from todo_user"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="gmt_created", property="gmtCreated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="pwd", property="pwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="encrypt", property="encrypt", jdbcType=JdbcType.VARCHAR),
        @Result(column="lastpwd", property="lastpwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="pwdlength", property="pwdlength", jdbcType=JdbcType.VARCHAR),
        @Result(column="slat", property="slat", jdbcType=JdbcType.VARCHAR)
    })
    List<TodoUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_user
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    @Update({
        "update todo_user",
        "set gmt_created = #{gmtCreated,jdbcType=TIMESTAMP},",
          "gmt_modified = #{gmtModified,jdbcType=TIMESTAMP},",
          "pwd = #{pwd,jdbcType=VARCHAR},",
          "encrypt = #{encrypt,jdbcType=VARCHAR},",
          "lastpwd = #{lastpwd,jdbcType=VARCHAR},",
          "pwdlength = #{pwdlength,jdbcType=VARCHAR},",
          "slat = #{slat,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TodoUser record);
}