package com.todo.dao;

import com.todo.dataobject.TodoLoginUser;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface TodoLoginUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_login_user
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    @Delete({
        "delete from todo_login_user",
        "where userid = #{userid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_login_user
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    @Insert({
        "insert into todo_login_user (userid, gmt_created, ",
        "gmt_modified, gender, ",
        "nickname, avatar, ",
        "slogan, email, regtime)",
        "values (#{userid,jdbcType=VARCHAR}, #{gmtCreated,jdbcType=TIMESTAMP}, ",
        "#{gmtModified,jdbcType=TIMESTAMP}, #{gender,jdbcType=BIT}, ",
        "#{nickname,jdbcType=VARCHAR}, #{avatar,jdbcType=VARCHAR}, ",
        "#{slogan,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, #{regtime,jdbcType=TIMESTAMP})"
    })
    int insert(TodoLoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_login_user
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    @Select({
        "select",
        "userid, gmt_created, gmt_modified, gender, nickname, avatar, slogan, email, ",
        "regtime",
        "from todo_login_user",
        "where userid = #{userid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="userid", property="userid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="gmt_created", property="gmtCreated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gender", property="gender", jdbcType=JdbcType.BIT),
        @Result(column="nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="avatar", property="avatar", jdbcType=JdbcType.VARCHAR),
        @Result(column="slogan", property="slogan", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="regtime", property="regtime", jdbcType=JdbcType.TIMESTAMP)
    })
    TodoLoginUser selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_login_user
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    @Select({
        "select",
        "userid, gmt_created, gmt_modified, gender, nickname, avatar, slogan, email, ",
        "regtime",
        "from todo_login_user"
    })
    @Results({
        @Result(column="userid", property="userid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="gmt_created", property="gmtCreated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gender", property="gender", jdbcType=JdbcType.BIT),
        @Result(column="nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="avatar", property="avatar", jdbcType=JdbcType.VARCHAR),
        @Result(column="slogan", property="slogan", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="regtime", property="regtime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TodoLoginUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_login_user
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    @Update({
        "update todo_login_user",
        "set gmt_created = #{gmtCreated,jdbcType=TIMESTAMP},",
          "gmt_modified = #{gmtModified,jdbcType=TIMESTAMP},",
          "gender = #{gender,jdbcType=BIT},",
          "nickname = #{nickname,jdbcType=VARCHAR},",
          "avatar = #{avatar,jdbcType=VARCHAR},",
          "slogan = #{slogan,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "regtime = #{regtime,jdbcType=TIMESTAMP}",
        "where userid = #{userid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TodoLoginUser record);
}