package com.todo.dataobject;

import java.util.Date;

public class TodoLoginUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_login_user.userid
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_login_user.gmt_created
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_login_user.gmt_modified
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_login_user.gender
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    private boolean gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_login_user.nickname
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_login_user.avatar
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_login_user.slogan
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    private String slogan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_login_user.email
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_login_user.regtime
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    private Date regtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_login_user.userid
     *
     * @return the value of todo_login_user.userid
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_login_user.userid
     *
     * @param userid the value for todo_login_user.userid
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_login_user.gmt_created
     *
     * @return the value of todo_login_user.gmt_created
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_login_user.gmt_created
     *
     * @param gmtCreated the value for todo_login_user.gmt_created
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_login_user.gmt_modified
     *
     * @return the value of todo_login_user.gmt_modified
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_login_user.gmt_modified
     *
     * @param gmtModified the value for todo_login_user.gmt_modified
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_login_user.gender
     *
     * @return the value of todo_login_user.gender
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_login_user.gender
     *
     * @param gender the value for todo_login_user.gender
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_login_user.nickname
     *
     * @return the value of todo_login_user.nickname
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_login_user.nickname
     *
     * @param nickname the value for todo_login_user.nickname
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_login_user.avatar
     *
     * @return the value of todo_login_user.avatar
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_login_user.avatar
     *
     * @param avatar the value for todo_login_user.avatar
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_login_user.slogan
     *
     * @return the value of todo_login_user.slogan
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public String getSlogan() {
        return slogan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_login_user.slogan
     *
     * @param slogan the value for todo_login_user.slogan
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public void setSlogan(String slogan) {
        this.slogan = slogan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_login_user.email
     *
     * @return the value of todo_login_user.email
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_login_user.email
     *
     * @param email the value for todo_login_user.email
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_login_user.regtime
     *
     * @return the value of todo_login_user.regtime
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_login_user.regtime
     *
     * @param regtime the value for todo_login_user.regtime
     *
     * @mbg.generated Wed Dec 26 18:52:20 CST 2018
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
}