package com.todo.dataobject;

import java.util.Date;

public class TodoUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_user.id
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    private String id;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_user.gmt_created
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_user.gmt_modified
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_user.pwd
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_user.encrypt
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    private String encrypt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_user.lastpwd
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    private String lastpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_user.pwdlength
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    private String pwdlength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_user.slat
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    private String slat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_user.id
     *
     * @return the value of todo_user.id
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_user.id
     *
     * @param id the value for todo_user.id
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_user.gmt_created
     *
     * @return the value of todo_user.gmt_created
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_user.gmt_created
     *
     * @param gmtCreated the value for todo_user.gmt_created
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_user.gmt_modified
     *
     * @return the value of todo_user.gmt_modified
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_user.gmt_modified
     *
     * @param gmtModified the value for todo_user.gmt_modified
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_user.pwd
     *
     * @return the value of todo_user.pwd
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_user.pwd
     *
     * @param pwd the value for todo_user.pwd
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_user.encrypt
     *
     * @return the value of todo_user.encrypt
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public String getEncrypt() {
        return encrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_user.encrypt
     *
     * @param encrypt the value for todo_user.encrypt
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public void setEncrypt(String encrypt) {
        this.encrypt = encrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_user.lastpwd
     *
     * @return the value of todo_user.lastpwd
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public String getLastpwd() {
        return lastpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_user.lastpwd
     *
     * @param lastpwd the value for todo_user.lastpwd
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public void setLastpwd(String lastpwd) {
        this.lastpwd = lastpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_user.pwdlength
     *
     * @return the value of todo_user.pwdlength
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public String getPwdlength() {
        return pwdlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_user.pwdlength
     *
     * @param pwdlength the value for todo_user.pwdlength
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public void setPwdlength(String pwdlength) {
        this.pwdlength = pwdlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_user.slat
     *
     * @return the value of todo_user.slat
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public String getSlat() {
        return slat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_user.slat
     *
     * @param slat the value for todo_user.slat
     *
     * @mbg.generated Wed Dec 26 18:51:54 CST 2018
     */
    public void setSlat(String slat) {
        this.slat = slat;
    }
}